---
# - name: determine whether it's Ubuntu or Linux Mint
#   set_fact:
#     distribution: "{{ ansible_distribution | lower }}"

# - name: fetch Ubuntu codename | Linux Mint
#   shell: sed 's/UBUNTU_CODENAME=//;t;d' /etc/os-release
#   register: os_release
#   run_once: true
#   when: distribution == "linux mint"

# - name: set_fact for codename | Linux Mint
#   set_fact:
#     codename: "{{ os_release.stdout }}"
#   when: distribution == "linux mint"

# - name: set_fact for codename | Ubuntu
#   set_fact:
#     codename: "{{ ansible_facts['lsb']['codename'] }}"
#   when: distribution == "ubuntu"

# - name: add apt key
#   apt_key:
#     url: http://ppa.launchpad.net/regolith-linux/release/ubuntu {{ codename }} InRelease
#     # keyserver: keyserver.ubuntu.com
#     # id: 4096R/EFC31B0AE9F1000B38E37FC8C0930F305A0E0FEF
#     id: EFC31B0AE9F1000B38E37FC8C0930F305A0E0FEF

# - name: add apt key
#   shell: >
#     curl -sL "https://keyserver.ubuntu.com/pks/lookup?fingerprint=on&op=index&search=0xEFC31B0AE9F1000B38E37FC8C0930F305A0E0FEF" | sudo apt-key add
#   args:
#     warn: false

# - name: add regolith ppa for i3-gaps
#   apt_repository:
#     repo: deb http://ppa.launchpad.net/regolith-linux/release/ubuntu {{ codename }} main
#     state: present
#   become: true

- name: "Check if software-properties-common is installed"
  package_facts:
    manager: "auto"

- name: ensure ppas can be added
  command: apt-get -yq install software-properties-common
  environment:
    DEBIAN_FRONTEND: noninteractive
  become: true
  when: "'software-properties-common' not in ansible_facts.packages"

- name: add regolith ppa for i3-gaps
  command: add-apt-repository ppa:regolith-linux/release -y
  changed_when: false
  become: true

- name: ensure i3-gaps is installed
  apt:
    name: "{{ i3_gaps_package_name }}"
    state: present
    update_cache: true
  become: true
