---
# https://i3wm.org/docs/repositories.html
- name: ensure i3-wm is installed
  apt:
    name: "{{ [i3_package_name] + i3_shared_packages }}"
    state: present
  when: i3

- name: install i3-gaps via PPA
  include_tasks: i3-gaps-ppa.yml
  when: i3_gaps_ppa

- name: install i3-extras
  include_tasks: i3-extras.yml
  when: i3_extras
