---
- name: Converge
  hosts: all
  vars:
    i3_gaps_git_path: "/home/.cache/i3-gaps-git"

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600

    # - apt:
    #     name: curl
    #     state: present

  tasks:
    - name: "Include ansible-role-i3"
      include_role:
        name: "ansible-role-i3"
