---
- name: Verify
  hosts: all

  tasks:
    - name: Collect package facts.
      package_facts:
        manager: "auto"

    # - name: Verify i3 is installed.
    #   assert:
    #     that:
    #       - "'i3-wm' in ansible_facts.packages"
    #     success_msg: "i3 is installed."
    #     fail_msg: "i3 is not installed."
